version: '3.8'

services:
  database:
    image: postgres:latest
    container_name: diploma-db
    volumes:
      - ./iaff_back/postgres_dump.sql:/docker-entrypoint-initdb.d/postgres_dump.sql
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "!"
      POSTGRES_DB: "ClientDatabase"
    ports:
      - "5432:5432"
    networks:
      - localnet

  backend:
    build: ./iaff_back
    ports:
      - "5001:5001"
    depends_on:
      - database
    networks:
      - localnet

  assistant:
    build: ./iaff_assistant
    ports:
      - "8085:8085"
    depends_on:
      - database
      - backend
    networks:
      - localnet

  frontend:
    build: ./iaff_front
    ports:
      - "3000:3000"
    depends_on:
      - database
      - backend
      - assistant
    networks:
      - localnet

  nginx:
    image: nginx:1.15-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot

  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot

networks:
  localnet: