version: '3.8'

services:
  backend:
    build: ./iaff_back
    ports:
      - "5000:5000"
    depends_on:
      - database

  frontend:
    build: ./iaff_front
    ports:
      - "3000:3000"

  assistant:
    build: ./iaff_assistant
    ports:
      - "8085:8085"
    depends_on:
      - database

  database:
    image: postgres:latest
    container_name: diploma-postgres
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "!"
      POSTGRES_DB: "clientdb"
    ports:
      - "5432:5432"